### ISSUE TITLE
Pdf font size?

### ISSUE THREAD

**Issue by tin2tin** [Tagirijus/fountain2pdf#1]
I've tested the fountain2pdf export. Here the bold etc. is working, but it seems like the font size and style (Courier 12) needs to be set: 
![image](https://user-images.githubusercontent.com/1322593/68615640-c6489200-04c3-11ea-8746-71d550146bfc.png)
I know nothing about the module you're using, but maybe this link might be useful? 
https://stackoverflow.com/questions/4899885/how-to-set-any-font-in-reportlab-canvas-in-python/4900031#4900031

**Comment by AndreaMonzini** [comment]
@tin2tin 
Is possible to export the  PDF directly from Blender?

**Comment by AndreaMonzini** [comment]
Could the Courier Prime be used with the export?

https://quoteunquoteapps.com/courierprime/index.php

**Comment by Tagirijus** [comment]
Hey there! A style can be set up in the `fountain2pdf_style_radioplay.py` file. Or you copy it and change the first line of `fountain2pdf.py` to use your specific style.

Maybe some day I will make it less clumsy to chose your own style - like it is now it is stupid, I know. Every new pull will make the changes gone etc. At the moment I cannot promise that an improvement will come soon, since I am doing this as a hobby and for my own needs mainly.

And maybe I will also be able to explain this styling a bit in the future ... ~~while I have to admit that I also only used a style I once found and tried to adept it to my needs~~. So basically what you get with the "default" export is my style **I** like for my radio play scripts. (-;

In such a style file you can set up the font and the font size of all the elements individually, by the way.

**Comment by tin2tin** [comment]
Ah, thank you. A learning curve here. Can you point my to the original style file. Could be useful if it is more screenplay friendly.

**Comment by Tagirijus** [comment]
I looked at the style again and it seems like I did not find another style and modified it, but I probably wrote it on my own, haha. Sorry for that! Either that or I really forgot a source!

Anyway feel free to just look into the style files (`fountain2pdf_style_...py`). I tried to work with placeholders so that it should be quite easy to modify the style or make your own style. For example the font can be set by just changign the font name for the variables beginnign with `FONT`. `SIZE` should be self-explaining, and so on.
